# Generated by Django 3.2.3 on 2021-05-29 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('first_name', models.CharField(help_text='Enter First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=100)),
                ('province', models.CharField(help_text='Enter the abbreviated         form of Province', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt_first_name', models.CharField(blank=True, help_text='Enter        Alternative First Name', max_length=100, null=True)),
                ('alt_last_name', models.CharField(blank=True, help_text='Enter         Alternative Last Name', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('first_name', models.CharField(help_text='Enter First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, help_text='Enter the abbreviated         form of Province', max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField(choices=[(1, 'STRONG'), (2, 'POSSIBLE'), (3, 'WEAK')], default=0)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.notice')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.record')),
            ],
        ),
    ]
